name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Start Docker Compose services
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: sleep 30

    - name: Check running containers
      run: docker ps -a

#    - name: Check logs
#      run: docker logs backend

    - name: Run Playwright tests
      run: docker-compose run --rm -T tests npx playwright test --reporter=json,html --output=playwright-reports

#    - name: Run Playwright tests
#      run: npx playwright test --reporter=json,html > playwright-results.json
#
    - name: Extract Summary and Show in CI
      run: |
        PASSED=$(jq '[.suites[].specs[].tests[] | select(.status=="passed")] | length' playwright-results.json)
        FAILED=$(jq '[.suites[].specs[].tests[] | select(.status=="failed")] | length' playwright-results.json)
        echo "### Playwright Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Passed: $PASSED" >> $GITHUB_STEP_SUMMARY
        echo "- ❌ Failed: $FAILED" >> $GITHUB_STEP_SUMMARY
    - name: Stop and clean up
      run: docker-compose down
