name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install Playwright with dependencies
      run: npx playwright install

    - name: install Express with dependencies
      run: npm install express

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Start Docker Compose services
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: sleep 30

    - name: Check running containers
      run: docker ps -a

    - name: Run Playwright tests & cleanup
      run: |
        docker-compose up --build -d # Start in detached mode
        docker-compose exec app npx playwright test
        docker-compose down

