name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose -f docker-compose.yml -f up -d

    - name: Check running containers
      run: docker ps -a

    - name: Check logs
      run: docker logs backend
